EditionID=inscryption_act2_cardpack
CardID=003_attack_conduit
RarityLevel=com
Name=Attack Conduit
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/003_attack_conduit(technology)_com