EditionID=inscryption_act2_cardpack
CardID=008_blue_mage
RarityLevel=com
Name=Blue Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/008_blue_mage(magicks)_com