EditionID=inscryption_act2_cardpack
CardID=010_lonely_wizard
RarityLevel=anc
Name=Lonely Wizard
Category=Magicks
DropWeight=2
Description=
IllustrationPath=inscryption_act2_cardpack/010_lonely_wizard(magicks)_anc