EditionID=inscryption_act2_cardpack
CardID=012_bombmaiden
RarityLevel=common
Name=Bombmaiden
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/012_bombmaiden