EditionID=inscryption_act2_cardpack
CardID=018_burrowingtrap
RarityLevel=common
Name=Burrowingtrap
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/018_burrowingtrap