EditionID=inscryption_act2_cardpack
CardID=020_undead_cat
RarityLevel=unc
Name=Undead Cat
Category=Undead
DropWeight=5
Description=
IllustrationPath=inscryption_act2_cardpack/020_undead_cat(undead)_unc