EditionID=inscryption_act2_cardpack
CardID=026_pharoh_s_pets
RarityLevel=com
Name=Pharoh's Pets
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/026_pharoh's_pets(undead)_com