EditionID=inscryption_act2_cardpack
CardID=029_drowned_soul
RarityLevel=rare
Name=Drowned Soul
Category=Undead
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/029_drowned_soul(undead)_rare