EditionID=inscryption_act2_cardpack
CardID=035_factory_conduit
RarityLevel=com
Name=Factory Conduit
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/035_factory_conduit(technology)_com