EditionID=inscryption_act2_cardpack
CardID=037_field_mice
RarityLevel=com
Name=Field Mice
Category=Nature
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/037_field_mice(nature)_com