EditionID=inscryption_act2_cardpack
CardID=038_spore_mice
RarityLevel=unc
Name=Spore Mice
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_cardpack/038_spore_mice(nature)_unc