EditionID=inscryption_act2_cardpack
CardID=040_force_mage
RarityLevel=com
Name=Force Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/040_force_mage(magicks)_com