EditionID=inscryption_act2_cardpack
CardID=041_franknstein
RarityLevel=common
Name=Franknstein
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/041_franknstein