EditionID=inscryption_act2_cardpack
CardID=043_ghost_ship
RarityLevel=com
Name=Ghost Ship
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/043_ghost_ship(undead)_com