EditionID=inscryption_act2_cardpack
CardID=044_grave_digger
RarityLevel=com
Name=Grave Digger
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/044_grave_digger(undead)_com