EditionID=inscryption_act2_cardpack
CardID=046_green_mage
RarityLevel=com
Name=Green Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/046_green_mage(magicks)_com