EditionID=inscryption_act2_cardpack
CardID=047_greenwizard
RarityLevel=common
Name=Greenwizard
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/047_greenwizard