EditionID=inscryption_act2_cardpack
CardID=050_headlesshorseman
RarityLevel=common
Name=Headlesshorseman
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/050_headlesshorseman