EditionID=inscryption_act2_cardpack
CardID=052_insectodrone
RarityLevel=com
Name=Insectodrone
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/052_insectodrone(technology)_com