EditionID=inscryption_act2_cardpack
CardID=054_junior_sage
RarityLevel=com
Name=Junior Sage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/054_junior_sage(magicks)_com