EditionID=inscryption_act2_cardpack
CardID=055_kingfisher
RarityLevel=com
Name=Kingfisher
Category=Nature
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/055_kingfisher(nature)_com