EditionID=inscryption_act2_cardpack
CardID=055_kingfisher
RarityLevel=common
Name=Kingfisher
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/055_kingfisher