EditionID=inscryption_act2_cardpack
CardID=058_mage_knight
RarityLevel=com
Name=Mage Knight
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/058_mage_knight(magicks)_com