EditionID=inscryption_act2_cardpack
CardID=059_mantis_god
RarityLevel=rare
Name=Mantis God
Category=Nature
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/059_mantis_god(nature)_rare