EditionID=inscryption_act2_cardpack
CardID=060_marrowmage
RarityLevel=common
Name=Marrowmage
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/060_marrowmage