EditionID=inscryption_act2_cardpack
CardID=061_masterbleene
RarityLevel=common
Name=Masterbleene
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/061_masterbleene