EditionID=inscryption_act2_cardpack
CardID=061_master_bleene
RarityLevel=rare
Name=Master Bleene
Category=Magicks
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/061_master_bleene(magicks)_rare