EditionID=inscryption_act2_cardpack
CardID=062_mastergoranj
RarityLevel=common
Name=Mastergoranj
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/062_mastergoranj