EditionID=inscryption_act2_cardpack
CardID=063_master_orlu
RarityLevel=rare
Name=Master Orlu
Category=Magicks
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/063_master_orlu(magicks)_rare