EditionID=inscryption_act2_cardpack
CardID=063_masterorlu
RarityLevel=common
Name=Masterorlu
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/063_masterorlu