EditionID=inscryption_act2_cardpack
CardID=074_sapphire_mox
RarityLevel=com
Name=Sapphire Mox
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/074_sapphire_mox(magicks)_com