EditionID=inscryption_act2_cardpack
CardID=077_muscle_mage
RarityLevel=com
Name=Muscle Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/077_muscle_mage(magicks)_com