EditionID=inscryption_act2_cardpack
CardID=079_nullconduit
RarityLevel=common
Name=Nullconduit
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/079_nullconduit