EditionID=inscryption_act2_cardpack
CardID=081_orange_mage
RarityLevel=com
Name=Orange Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/081_orange_mage(magicks)_com