EditionID=inscryption_act2_cardpack
CardID=085_practice_wizard
RarityLevel=com
Name=Practice Wizard
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/085_practice_wizard(magicks)_com