EditionID=inscryption_act2_cardpack
CardID=086_prospector
RarityLevel=common
Name=Prospector
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/086_prospector