EditionID=inscryption_act2_cardpack
CardID=086_prospector
RarityLevel=anc
Name=Prospector
Category=Nature
DropWeight=2
Description=
IllustrationPath=inscryption_act2_cardpack/086_prospector(nature)_anc