EditionID=inscryption_act2_cardpack
CardID=087_mage_pupil
RarityLevel=com
Name=Mage Pupil
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/087_mage_pupil(magicks)_com