EditionID=inscryption_act2_cardpack
CardID=091_steel_mice
RarityLevel=com
Name=Steel Mice
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/091_steel_mice(technology)_com