EditionID=inscryption_act2_cardpack
CardID=095_sarcophagus
RarityLevel=com
Name=Sarcophagus
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/095_sarcophagus(undead)_com