EditionID=inscryption_act2_cardpack
CardID=098_sentrybot_fused
RarityLevel=common
Name=Sentrybot Fused
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/098_sentrybot_fused