EditionID=inscryption_act2_cardpack
CardID=101_skelemagus
RarityLevel=com
Name=Skelemagus
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/101_skelemagus(undead)_com