EditionID=inscryption_act2_cardpack
CardID=101_skeletonmage
RarityLevel=common
Name=Skeletonmage
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/101_skeletonmage