EditionID=inscryption_act2_cardpack
CardID=102_bell_tentacle
RarityLevel=unc
Name=Bell Tentacle
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_cardpack/102_bell_tentacle(nature)_unc