EditionID=inscryption_act2_cardpack
CardID=103_hand_tentacle
RarityLevel=unc
Name=Hand Tentacle
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_cardpack/103_hand_tentacle(nature)_unc