EditionID=inscryption_act2_cardpack
CardID=104_mirror_tentacle
RarityLevel=com
Name=Mirror Tentacle
Category=Nature
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/104_mirror_tentacle(nature)_com