EditionID=inscryption_act2_cardpack
CardID=104_squidmirror
RarityLevel=common
Name=Squidmirror
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/104_squidmirror