EditionID=inscryption_act2_cardpack
CardID=107_starvation
RarityLevel=unc
Name=Starvation
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=inscryption_act2_cardpack/107_starvation_unc