EditionID=inscryption_act2_cardpack
CardID=109_stim_mage
RarityLevel=com
Name=Stim Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/109_stim_mage(magicks)_com