EditionID=inscryption_act2_cardpack
CardID=111_mox_module
RarityLevel=rare
Name=Mox Module
Category=Technology
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/111_mox_module(technology)_rare