EditionID=inscryption_act2_cardpack
CardID=111_techmoxtriple
RarityLevel=common
Name=Techmoxtriple
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/111_techmoxtriple