EditionID=inscryption_act2_cardpack
CardID=112_thick_droid
RarityLevel=com
Name=Thick Droid
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_cardpack/112_thick_droid(technology)_com