EditionID=inscryption_act2_cardpack
CardID=113_tomb_robber
RarityLevel=rare
Name=Tomb Robber
Category=Undead
DropWeight=3
Description=
IllustrationPath=inscryption_act2_cardpack/113_tomb_robber(undead)_rare