EditionID=digimon_world_next_order
CardID=003_agumon_black
RarityLevel=com
Name=Agumon Black
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/003_agumon_black_com