EditionID=digimon_world_next_order
CardID=012_ancientgarurumon
RarityLevel=anc
Name=Ancientgarurumon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/012_ancientgarurumon_anc