EditionID=digimon_world_next_order
CardID=016_ancientmermaidmon
RarityLevel=anc
Name=Ancientmermaidmon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/016_ancientmermaidmon_anc