EditionID=digimon_world_next_order
CardID=017_ancientsphinxmon
RarityLevel=anc
Name=Ancientsphinxmon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/017_ancientsphinxmon_anc