EditionID=digimon_world_next_order
CardID=018_ancienttroymon
RarityLevel=anc
Name=Ancienttroymon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/018_ancienttroymon_anc