EditionID=digimon_world_next_order
CardID=020_ancientwisemon
RarityLevel=anc
Name=Ancientwisemon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/020_ancientwisemon_anc