EditionID=digimon_world_next_order
CardID=032_armageddemon
RarityLevel=leg
Name=Armageddemon
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/032_armageddemon_leg