EditionID=digimon_world_next_order
CardID=039_bancholeomon
RarityLevel=rare
Name=Bancholeomon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/039_bancholeomon_rare