EditionID=digimon_world_next_order
CardID=046_belphemon_sleep_mode
RarityLevel=anc
Name=Belphemon Sleep Mode
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/046_belphemon_sleep_mode_anc