EditionID=digimon_world_next_order
CardID=053_blackgatomon
RarityLevel=com
Name=Blackgatomon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/053_blackgatomon_com