EditionID=digimon_world_next_order
CardID=054_blackgrowlmon
RarityLevel=com
Name=Blackgrowlmon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/054_blackgrowlmon_com