EditionID=digimon_world_next_order
CardID=074_cerberusmon
RarityLevel=unc
Name=Cerberusmon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/074_cerberusmon_unc