EditionID=digimon_world_next_order
CardID=082_cherubimon_black
RarityLevel=anc
Name=Cherubimon Black
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/082_cherubimon_black_anc