EditionID=digimon_world_next_order
CardID=099_cyberdramon
RarityLevel=unc
Name=Cyberdramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/099_cyberdramon_unc