EditionID=digimon_world_next_order
CardID=113_dexdorugreymon
RarityLevel=unc
Name=Dexdorugreymon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/113_dexdorugreymon_unc