EditionID=digimon_world_next_order
CardID=119_dinotigermon
RarityLevel=rare
Name=Dinotigermon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/119_dinotigermon_rare