EditionID=digimon_world_next_order
CardID=125_dorugreymon
RarityLevel=unc
Name=Dorugreymon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/125_dorugreymon_unc