EditionID=digimon_world_next_order
CardID=145_flamedramon
RarityLevel=unc
Name=Flamedramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/145_flamedramon_unc