EditionID=digimon_world_next_order
CardID=162_gargoylemon
RarityLevel=unc
Name=Gargoylemon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/162_gargoylemon_unc