EditionID=digimon_world_next_order
CardID=165_garurumon_black
RarityLevel=com
Name=Garurumon Black
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/165_garurumon_black_com