EditionID=digimon_world_next_order
CardID=175_gigaseadramon
RarityLevel=rare
Name=Gigaseadramon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/175_gigaseadramon_rare