EditionID=digimon_world_next_order
CardID=182_goldnumemon
RarityLevel=rare
Name=Goldnumemon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/182_goldnumemon_rare