EditionID=digimon_world_next_order
CardID=184_goldveedramon
RarityLevel=unc
Name=Goldveedramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/184_goldveedramon_unc