EditionID=digimon_world_next_order
CardID=188_grandiskuwagamon
RarityLevel=rare
Name=Grandiskuwagamon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/188_grandiskuwagamon_rare