EditionID=digimon_world_next_order
CardID=189_grandracmon
RarityLevel=rare
Name=Grandracmon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/189_grandracmon_rare