EditionID=digimon_world_next_order
CardID=207_hiandromon
RarityLevel=rare
Name=Hiandromon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/207_hiandromon_rare