EditionID=digimon_world_next_order
CardID=214_imperialdramon
RarityLevel=leg
Name=Imperialdramon
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/214_imperialdramon_leg