EditionID=digimon_world_next_order
CardID=215_imperialdramon_fighter_mode
RarityLevel=leg
Name=Imperialdramon Fighter Mode
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/215_imperialdramon_fighter_mode_leg