EditionID=digimon_world_next_order
CardID=227_kabuterimon
RarityLevel=com
Name=Kabuterimon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/227_kabuterimon_com