EditionID=digimon_world_next_order
CardID=274_lucemon_rival
RarityLevel=anc
Name=Lucemon Rival
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/274_lucemon_rival_anc