EditionID=digimon_world_next_order
CardID=275_lucemon_shadowlord_mode
RarityLevel=leg
Name=Lucemon Shadowlord Mode
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/275_lucemon_shadowlord_mode_leg