EditionID=digimon_world_next_order
CardID=278_machgaogamon
RarityLevel=unc
Name=Machgaogamon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/278_machgaogamon_unc