EditionID=digimon_world_next_order
CardID=279_machinedramon
RarityLevel=rare
Name=Machinedramon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/279_machinedramon_rare