EditionID=digimon_world_next_order
CardID=284_magnamon_alt
RarityLevel=unc
Name=Magnamon Alt
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/284_magnamon_alt_unc