EditionID=digimon_world_next_order
CardID=294_marineangemon
RarityLevel=rare
Name=Marineangemon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/294_marineangemon_rare