EditionID=digimon_world_next_order
CardID=302_megakabuterimon
RarityLevel=unc
Name=Megakabuterimon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/302_megakabuterimon_unc