EditionID=digimon_world_next_order
CardID=303_megaseadramon
RarityLevel=unc
Name=Megaseadramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/303_megaseadramon_unc