EditionID=digimon_world_next_order
CardID=309_metalgarurumon
RarityLevel=rare
Name=Metalgarurumon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/309_metalgarurumon_rare