EditionID=digimon_world_next_order
CardID=312_metalgreymon_blue
RarityLevel=unc
Name=Metalgreymon Blue
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/312_metalgreymon_blue_unc