EditionID=digimon_world_next_order
CardID=314_metalkoromon
RarityLevel=com
Name=Metalkoromon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/314_metalkoromon_com