EditionID=digimon_world_next_order
CardID=317_metalpiranimon
RarityLevel=rare
Name=Metalpiranimon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/317_metalpiranimon_rare