EditionID=digimon_world_next_order
CardID=319_metaltyrannomon
RarityLevel=unc
Name=Metaltyrannomon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/319_metaltyrannomon_unc