EditionID=digimon_world_next_order
CardID=325_miragegaogamon
RarityLevel=unc
Name=Miragegaogamon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/325_miragegaogamon_unc