EditionID=digimon_world_next_order
CardID=328_monochromon
RarityLevel=com
Name=Monochromon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/328_monochromon_com