EditionID=digimon_world_next_order
CardID=331_moonmillenniummon
RarityLevel=anc
Name=Moonmillenniummon
Category=Uncategorized
DropWeight=2
Description=
IllustrationPath=digimon_world_next_order/331_moonmillenniummon_anc