EditionID=digimon_world_next_order
CardID=336_murmukusmon
RarityLevel=rare
Name=Murmukusmon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/336_murmukusmon_rare