EditionID=digimon_world_next_order
CardID=351_omegamon_alter_b
RarityLevel=leg
Name=Omegamon Alter B
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/351_omegamon_alter_b_leg