EditionID=digimon_world_next_order
CardID=373_petaldramon
RarityLevel=unc
Name=Petaldramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/373_petaldramon_unc