EditionID=digimon_world_next_order
CardID=379_platinumnumemon
RarityLevel=rare
Name=Platinumnumemon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/379_platinumnumemon_rare