EditionID=digimon_world_next_order
CardID=386_princemamemon
RarityLevel=rare
Name=Princemamemon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/386_princemamemon_rare