EditionID=digimon_world_next_order
CardID=396_rapidmon_armor
RarityLevel=unc
Name=Rapidmon Armor
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/396_rapidmon_armor_unc