EditionID=digimon_world_next_order
CardID=408_rizegreymon
RarityLevel=unc
Name=Rizegreymon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/408_rizegreymon_unc