EditionID=digimon_world_next_order
CardID=415_sagittarimon
RarityLevel=unc
Name=Sagittarimon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/415_sagittarimon_unc