EditionID=digimon_world_next_order
CardID=421_sangloupmon
RarityLevel=com
Name=Sangloupmon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/421_sangloupmon_com