EditionID=digimon_world_next_order
CardID=438_shinegreymon_burst_mode
RarityLevel=rare
Name=Shinegreymon Burst Mode
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/438_shinegreymon_burst_mode_rare