EditionID=digimon_world_next_order
CardID=448_shoutmon_x7
RarityLevel=leg
Name=Shoutmon X7
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/448_shoutmon_x7_leg