EditionID=digimon_world_next_order
CardID=453_skullgreymon
RarityLevel=unc
Name=Skullgreymon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/453_skullgreymon_unc