EditionID=digimon_world_next_order
CardID=454_skullmammothmon
RarityLevel=rare
Name=Skullmammothmon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/454_skullmammothmon_rare