EditionID=digimon_world_next_order
CardID=455_skullmeramon
RarityLevel=unc
Name=Skullmeramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/455_skullmeramon_unc