EditionID=digimon_world_next_order
CardID=457_snowgoblimon
RarityLevel=com
Name=Snowgoblimon
Category=Uncategorized
DropWeight=10
Description=
IllustrationPath=digimon_world_next_order/457_snowgoblimon_com