EditionID=digimon_world_next_order
CardID=477_thunderbirdmon
RarityLevel=unc
Name=Thunderbirdmon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/477_thunderbirdmon_unc