EditionID=digimon_world_next_order
CardID=509_vikaralamon
RarityLevel=unc
Name=Vikaralamon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/509_vikaralamon_unc