EditionID=digimon_world_next_order
CardID=513_vulcanusmon
RarityLevel=leg
Name=Vulcanusmon
Category=Uncategorized
DropWeight=1
Description=
IllustrationPath=digimon_world_next_order/513_vulcanusmon_leg