EditionID=digimon_world_next_order
CardID=515_wargreymon
RarityLevel=rare
Name=Wargreymon
Category=Uncategorized
DropWeight=3
Description=
IllustrationPath=digimon_world_next_order/515_wargreymon_rare