EditionID=digimon_world_next_order
CardID=519_warumonzaemon
RarityLevel=unc
Name=Warumonzaemon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/519_warumonzaemon_unc