EditionID=digimon_world_next_order
CardID=520_waruseadramon
RarityLevel=unc
Name=Waruseadramon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/520_waruseadramon_unc