EditionID=digimon_world_next_order
CardID=522_weregarurumon
RarityLevel=unc
Name=Weregarurumon
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/522_weregarurumon_unc