EditionID=digimon_world_next_order
CardID=523_weregarurumon_black
RarityLevel=unc
Name=Weregarurumon Black
Category=Uncategorized
DropWeight=5
Description=
IllustrationPath=digimon_world_next_order/523_weregarurumon_black_unc