EditionID=kantai_collection
CardID=012_akatsuki_kai
RarityLevel=uncommon
Name=Akatsuki Kai
Category=Akatsuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/012_akatsuki_kai