EditionID=kantai_collection
CardID=021_akishimo_kai
RarityLevel=uncommon
Name=Akishimo Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/021_akishimo_kai