EditionID=kantai_collection
CardID=024_akitsushima
RarityLevel=common
Name=Akitsushima
Category=Akitsushima Class Seaplane Tender
DropWeight=10
Description=
IllustrationPath=kantai_collection/024_akitsushima