EditionID=kantai_collection
CardID=031_amagiri_kai_ni
RarityLevel=rare
Name=Amagiri Kai Ni
Category=Ayanami Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/031_amagiri_kai_ni