EditionID=kantai_collection
CardID=035_amatsukaze_kai
RarityLevel=uncommon
Name=Amatsukaze Kai
Category=Kagerou Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/035_amatsukaze_kai