EditionID=kantai_collection
CardID=040_aquila_kai
RarityLevel=uncommon
Name=Aquila Kai
Category=Aquila Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/040_aquila_kai