EditionID=kantai_collection
CardID=048_arashio_kai_ni
RarityLevel=rare
Name=Arashio Kai Ni
Category=Asashio Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/048_arashio_kai_ni