EditionID=kantai_collection
CardID=065_asashio_kai_ni_d
RarityLevel=ancient
Name=Asashio Kai Ni D
Category=Asashio Class Destroyer
DropWeight=2
Description=
IllustrationPath=kantai_collection/065_asashio_kai_ni_d