EditionID=kantai_collection
CardID=078_bismarck_kai
RarityLevel=uncommon
Name=Bismarck Kai
Category=Bismarck Class Fast Battleship
DropWeight=5
Description=
IllustrationPath=kantai_collection/078_bismarck_kai