EditionID=kantai_collection
CardID=079_bismarck_zwei
RarityLevel=rare
Name=Bismarck Zwei
Category=Bismarck Class Fast Battleship
DropWeight=3
Description=
IllustrationPath=kantai_collection/079_bismarck_zwei