EditionID=kantai_collection
CardID=082_c.cappellini
RarityLevel=common
Name=C Cappellini
Category=Marcello Class Submarine
DropWeight=10
Description=
IllustrationPath=kantai_collection/082_c_cappellini