EditionID=kantai_collection
CardID=089_chitose_kai
RarityLevel=uncommon
Name=Chitose Kai
Category=Chitose Class Seaplane Tender
DropWeight=5
Description=
IllustrationPath=kantai_collection/089_chitose_kai