EditionID=kantai_collection
CardID=089_chitose_kou_kai
RarityLevel=uncommon
Name=Chitose Kou Kai
Category=Chitose Class Light Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/089_chitose_kou_kai