EditionID=kantai_collection
CardID=092_chitose_kou_kai_ni
RarityLevel=rare
Name=Chitose Kou Kai Ni
Category=Chitose Class Light Carrier
DropWeight=3
Description=
IllustrationPath=kantai_collection/092_chitose_kou_kai_ni