EditionID=kantai_collection
CardID=095_chiyoda_kai
RarityLevel=uncommon
Name=Chiyoda Kai
Category=Chitose Class Seaplane Tender
DropWeight=5
Description=
IllustrationPath=kantai_collection/095_chiyoda_kai