EditionID=kantai_collection
CardID=098_chiyoda_kou_kai_ni
RarityLevel=rare
Name=Chiyoda Kou Kai Ni
Category=Chitose Class Light Carrier
DropWeight=3
Description=
IllustrationPath=kantai_collection/098_chiyoda_kou_kai_ni