EditionID=kantai_collection
CardID=102_choukai_kai
RarityLevel=uncommon
Name=Choukai Kai
Category=Takao Class Heavy Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/102_choukai_kai