EditionID=kantai_collection
CardID=106_commandant_teste
RarityLevel=common
Name=Commandant Teste
Category=Commandant Teste Class Seaplane Tender
DropWeight=10
Description=
IllustrationPath=kantai_collection/106_commandant_teste