EditionID=kantai_collection
CardID=107_commandant_teste_kai
RarityLevel=uncommon
Name=Commandant Teste Kai
Category=Commandant Teste Class Seaplane Tender
DropWeight=5
Description=
IllustrationPath=kantai_collection/107_commandant_teste_kai