EditionID=kantai_collection
CardID=134_fumizuki_kai
RarityLevel=uncommon
Name=Fumizuki Kai
Category=Mutsuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/134_fumizuki_kai