EditionID=kantai_collection
CardID=143_fuyutsuki_kai
RarityLevel=uncommon
Name=Fuyutsuki Kai
Category=Akizuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/143_fuyutsuki_kai