EditionID=kantai_collection
CardID=144_gambier_bay
RarityLevel=common
Name=Gambier Bay
Category=Casablanca Class Light Carrier
DropWeight=10
Description=
IllustrationPath=kantai_collection/144_gambier_bay