EditionID=kantai_collection
CardID=148_gangut_dva
RarityLevel=uncommon
Name=Gangut Dva
Category=Gangut Class Fast Battleship
DropWeight=5
Description=
IllustrationPath=kantai_collection/148_gangut_dva