EditionID=kantai_collection
CardID=149_giuseppe_garibaldi
RarityLevel=common
Name=Giuseppe Garibaldi
Category=Duca degli Abruzzi Class Light Cruiser
DropWeight=10
Description=
IllustrationPath=kantai_collection/149_giuseppe_garibaldi