EditionID=kantai_collection
CardID=152_gotland_andra
RarityLevel=rare
Name=Gotland Andra
Category=Gotland Class Light Cruiser
DropWeight=3
Description=
IllustrationPath=kantai_collection/152_gotland_andra