EditionID=kantai_collection
CardID=155_graf_zeppelin_kai
RarityLevel=uncommon
Name=Graf Zeppelin Kai
Category=Graf Zeppelin Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/155_graf_zeppelin_kai