EditionID=kantai_collection
CardID=158_hachijou
RarityLevel=common
Name=Hachijou
Category=Shimushu Class Coastal Defense Ship
DropWeight=10
Description=
IllustrationPath=kantai_collection/158_hachijou