EditionID=kantai_collection
CardID=167_hamakaze_kai
RarityLevel=uncommon
Name=Hamakaze Kai
Category=Kagerou Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/167_hamakaze_kai