EditionID=kantai_collection
CardID=179_harusame_kai_ni
RarityLevel=rare
Name=Harusame Kai Ni
Category=Shiratsuyu Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/179_harusame_kai_ni