EditionID=kantai_collection
CardID=181_hatakaze_kai
RarityLevel=uncommon
Name=Hatakaze Kai
Category=Kamikaze Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/181_hatakaze_kai