EditionID=kantai_collection
CardID=193_hatsuzuki_kai
RarityLevel=uncommon
Name=Hatsuzuki Kai
Category=Akizuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/193_hatsuzuki_kai