EditionID=kantai_collection
CardID=195_hayanami_kai
RarityLevel=uncommon
Name=Hayanami Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/195_hayanami_kai