EditionID=kantai_collection
CardID=199_hayashio_kai
RarityLevel=uncommon
Name=Hayashio Kai
Category=Kagerou Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/199_hayashio_kai