EditionID=kantai_collection
CardID=207_heywood_l__edwards
RarityLevel=common
Name=Heywood L. Edwards
Category=Fletcher Class Destroyer
DropWeight=10
Description=
IllustrationPath=kantai_collection/207_heywood_l__edwards