EditionID=kantai_collection
CardID=220_hiryuu_kai
RarityLevel=uncommon
Name=Hiryuu Kai
Category=Hiryuu Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/220_hiryuu_kai