EditionID=kantai_collection
CardID=225_honolulu_kai
RarityLevel=uncommon
Name=Honolulu Kai
Category=Brooklyn Class Light Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/225_honolulu_kai