EditionID=kantai_collection
CardID=227_hornet_kai
RarityLevel=uncommon
Name=Hornet Kai
Category=Yorktown Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/227_hornet_kai