EditionID=kantai_collection
CardID=229_houshou_kai
RarityLevel=uncommon
Name=Houshou Kai
Category=Houshou Class Light Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/229_houshou_kai