EditionID=kantai_collection
CardID=281_ishigaki_kai
RarityLevel=uncommon
Name=Ishigaki Kai
Category=Shimushu Class Coastal Defense Ship
DropWeight=5
Description=
IllustrationPath=kantai_collection/281_ishigaki_kai