EditionID=kantai_collection
CardID=287_isonami_kai_ni
RarityLevel=rare
Name=Isonami Kai Ni
Category=Fubuki Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/287_isonami_kai_ni