EditionID=kantai_collection
CardID=301_jingei_kai
RarityLevel=uncommon
Name=Jingei Kai
Category=Jingei Class Submarine Tender
DropWeight=5
Description=
IllustrationPath=kantai_collection/301_jingei_kai