EditionID=kantai_collection
CardID=338_kasumi_kai_ni_b
RarityLevel=ancient
Name=Kasumi Kai Ni B
Category=Asashio Class Destroyer
DropWeight=2
Description=
IllustrationPath=kantai_collection/338_kasumi_kai_ni_b