EditionID=kantai_collection
CardID=340_katori_kai
RarityLevel=uncommon
Name=Katori Kai
Category=Katori Class Training Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/340_katori_kai