EditionID=kantai_collection
CardID=345_kawakaze_kai_ni
RarityLevel=rare
Name=Kawakaze Kai Ni
Category=Shiratsuyu Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/345_kawakaze_kai_ni