EditionID=kantai_collection
CardID=353_kinugasa_kai
RarityLevel=uncommon
Name=Kinugasa Kai
Category=Aoba Class Heavy Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/353_kinugasa_kai