EditionID=kantai_collection
CardID=358_kirishima_kai
RarityLevel=uncommon
Name=Kirishima Kai
Category=Kongou Class Fast Battleship
DropWeight=5
Description=
IllustrationPath=kantai_collection/358_kirishima_kai