EditionID=kantai_collection
CardID=361_kisaragi_kai
RarityLevel=uncommon
Name=Kisaragi Kai
Category=Mutsuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/361_kisaragi_kai