EditionID=kantai_collection
CardID=364_kishinami_kai
RarityLevel=uncommon
Name=Kishinami Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/364_kishinami_kai