EditionID=kantai_collection
CardID=372_kiyoshimo_kai
RarityLevel=uncommon
Name=Kiyoshimo Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/372_kiyoshimo_kai