EditionID=kantai_collection
CardID=373_kiyoshimo_kai_ni
RarityLevel=rare
Name=Kiyoshimo Kai Ni
Category=Yuugumo Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/373_kiyoshimo_kai_ni