EditionID=kantai_collection
CardID=391_kurahashi
RarityLevel=common
Name=Kurahashi
Category=Mikura Class Coastal Defense Ship
DropWeight=10
Description=
IllustrationPath=kantai_collection/391_kurahashi