EditionID=kantai_collection
CardID=392_kurahashi_kai
RarityLevel=uncommon
Name=Kurahashi Kai
Category=Mikura Class Coastal Defense Ship
DropWeight=5
Description=
IllustrationPath=kantai_collection/392_kurahashi_kai