EditionID=kantai_collection
CardID=399_libeccio_kai
RarityLevel=uncommon
Name=Libeccio Kai
Category=Maestrale Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/399_libeccio_kai