EditionID=kantai_collection
CardID=402_luigi_torelli_kai
RarityLevel=uncommon
Name=Luigi Torelli Kai
Category=Guglielmo Marconi Class Submarine
DropWeight=5
Description=
IllustrationPath=kantai_collection/402_luigi_torelli_kai