EditionID=kantai_collection
CardID=411_makinami_kai
RarityLevel=uncommon
Name=Makinami Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/411_makinami_kai