EditionID=kantai_collection
CardID=417_massachusetts_kai
RarityLevel=uncommon
Name=Massachusetts Kai
Category=South Dakota Class Fast Battleship
DropWeight=5
Description=
IllustrationPath=kantai_collection/417_massachusetts_kai