EditionID=kantai_collection
CardID=421_matsukaze_kai
RarityLevel=uncommon
Name=Matsukaze Kai
Category=Kamikaze Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/421_matsukaze_kai