EditionID=kantai_collection
CardID=423_matsuwa_kai
RarityLevel=uncommon
Name=Matsuwa Kai
Category=Etorofu Class Coastal Defense Ship
DropWeight=5
Description=
IllustrationPath=kantai_collection/423_matsuwa_kai