EditionID=kantai_collection
CardID=429_michishio_kai_ni
RarityLevel=rare
Name=Michishio Kai Ni
Category=Asashio Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/429_michishio_kai_ni