EditionID=kantai_collection
CardID=439_minazuki_kai
RarityLevel=uncommon
Name=Minazuki Kai
Category=Mutsuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/439_minazuki_kai