EditionID=kantai_collection
CardID=446_mizuho_kai
RarityLevel=uncommon
Name=Mizuho Kai
Category=Mizuho Class Seaplane Tender
DropWeight=5
Description=
IllustrationPath=kantai_collection/446_mizuho_kai