EditionID=kantai_collection
CardID=448_mochizuki_kai
RarityLevel=uncommon
Name=Mochizuki Kai
Category=Mutsuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/448_mochizuki_kai