EditionID=kantai_collection
CardID=456_murakumo_kai
RarityLevel=uncommon
Name=Murakumo Kai
Category=Fubuki Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/456_murakumo_kai