EditionID=kantai_collection
CardID=457_murakumo_kai_ni
RarityLevel=rare
Name=Murakumo Kai Ni
Category=Fubuki Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/457_murakumo_kai_ni