EditionID=kantai_collection
CardID=459_murasame_kai
RarityLevel=uncommon
Name=Murasame Kai
Category=Shiratsuyu Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/459_murasame_kai