EditionID=kantai_collection
CardID=463_musashi_kai_ni
RarityLevel=rare
Name=Musashi Kai Ni
Category=Yamato Class Battleship
DropWeight=3
Description=
IllustrationPath=kantai_collection/463_musashi_kai_ni