EditionID=kantai_collection
CardID=467_mutsuki_kai_ni
RarityLevel=rare
Name=Mutsuki Kai Ni
Category=Mutsuki Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/467_mutsuki_kai_ni