EditionID=kantai_collection
CardID=478_naganami_kai_ni
RarityLevel=rare
Name=Naganami Kai Ni
Category=Yuugumo Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/478_naganami_kai_ni