EditionID=kantai_collection
CardID=503_no_101_transport_ship
RarityLevel=common
Name=No 101 Transport Ship
Category=2nd Class Transporter Amphibious Assault Ship
DropWeight=10
Description=
IllustrationPath=kantai_collection/503_no_101_transport_ship