EditionID=kantai_collection
CardID=504_no_101_transport_ship_kai
RarityLevel=uncommon
Name=No 101 Transport Ship Kai
Category=2nd Class Transporter Amphibious Assault Ship
DropWeight=5
Description=
IllustrationPath=kantai_collection/504_no_101_transport_ship_kai