EditionID=kantai_collection
CardID=504_northampton_kai
RarityLevel=uncommon
Name=Northampton Kai
Category=Northampton Class Heavy Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/504_northampton_kai