EditionID=kantai_collection
CardID=508_noshiro_kai
RarityLevel=uncommon
Name=Noshiro Kai
Category=Agano Class Light Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/508_noshiro_kai