EditionID=kantai_collection
CardID=525_ooshio_kai_ni
RarityLevel=rare
Name=Ooshio Kai Ni
Category=Asashio Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/525_ooshio_kai_ni