EditionID=kantai_collection
CardID=547_ryuuhou_kai
RarityLevel=uncommon
Name=Ryuuhou Kai
Category=Ryuuhou Class Light Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/547_ryuuhou_kai