EditionID=kantai_collection
CardID=567_saratoga_kai
RarityLevel=uncommon
Name=Saratoga Kai
Category=Lexington Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/567_saratoga_kai