EditionID=kantai_collection
CardID=568_saratoga_mk_ii
RarityLevel=rare
Name=Saratoga Mk.ii
Category=Lexington Class Standard Aircraft Carrier
DropWeight=3
Description=
IllustrationPath=kantai_collection/568_saratoga_mk_ii