EditionID=kantai_collection
CardID=572_satsuki_kai_ni
RarityLevel=rare
Name=Satsuki Kai Ni
Category=Mutsuki Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/572_satsuki_kai_ni