EditionID=kantai_collection
CardID=592_shimakaze_kai
RarityLevel=uncommon
Name=Shimakaze Kai
Category=Shimakaze Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/592_shimakaze_kai