EditionID=kantai_collection
CardID=598_shinyou_kai
RarityLevel=uncommon
Name=Shinyou Kai
Category=Taiyou Class Light Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/598_shinyou_kai