EditionID=kantai_collection
CardID=604_shiranui_kai_ni
RarityLevel=rare
Name=Shiranui Kai Ni
Category=Kagerou Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/604_shiranui_kai_ni