EditionID=kantai_collection
CardID=606_shiratsuyu_kai
RarityLevel=uncommon
Name=Shiratsuyu Kai
Category=Shiratsuyu Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/606_shiratsuyu_kai