EditionID=kantai_collection
CardID=611_shouhou_kai
RarityLevel=uncommon
Name=Shouhou Kai
Category=Shouhou Class Light Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/611_shouhou_kai