EditionID=kantai_collection
CardID=619_souryuu_kai
RarityLevel=uncommon
Name=Souryuu Kai
Category=Souryuu Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/619_souryuu_kai