EditionID=kantai_collection
CardID=643_takanami_kai
RarityLevel=uncommon
Name=Takanami Kai
Category=Yuugumo Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/643_takanami_kai