EditionID=kantai_collection
CardID=656_tanikaze_kai
RarityLevel=uncommon
Name=Tanikaze Kai
Category=Kagerou Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/656_tanikaze_kai