EditionID=kantai_collection
CardID=658_tashkent_kai
RarityLevel=uncommon
Name=Tashkent Kai
Category=Tashkent Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/658_tashkent_kai