EditionID=kantai_collection
CardID=663_tenryuu_kai
RarityLevel=uncommon
Name=Tenryuu Kai
Category=Tenryuu Class Light Cruiser
DropWeight=5
Description=
IllustrationPath=kantai_collection/663_tenryuu_kai