EditionID=kantai_collection
CardID=668_tokitsukaze_kai
RarityLevel=uncommon
Name=Tokitsukaze Kai
Category=Kagerou Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/668_tokitsukaze_kai