EditionID=kantai_collection
CardID=688_unryuu_kai
RarityLevel=uncommon
Name=Unryuu Kai
Category=Unryuu Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/688_unryuu_kai