EditionID=kantai_collection
CardID=691_urakaze_d_kai
RarityLevel=rare
Name=Urakaze D Kai
Category=Kagerou Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/691_urakaze_d_kai