EditionID=kantai_collection
CardID=693_urakaze_d_kai
RarityLevel=rare
Name=Urakaze D Kai
Category=Kagerou Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/693_urakaze_d_kai