EditionID=kantai_collection
CardID=695_uranami_kai_ni
RarityLevel=rare
Name=Uranami Kai Ni
Category=Fubuki Class Destroyer
DropWeight=3
Description=
IllustrationPath=kantai_collection/695_uranami_kai_ni