EditionID=kantai_collection
CardID=750_yuudachi_kai
RarityLevel=uncommon
Name=Yuudachi Kai
Category=Shiratsuyu Class Destroyer
DropWeight=5
Description=
IllustrationPath=kantai_collection/750_yuudachi_kai