EditionID=kantai_collection
CardID=770_zuikaku
RarityLevel=common
Name=Zuikaku
Category=Shoukaku Class Standard Aircraft Carrier
DropWeight=10
Description=
IllustrationPath=kantai_collection/770_zuikaku