EditionID=kantai_collection
CardID=771_zuikaku_kai
RarityLevel=uncommon
Name=Zuikaku Kai
Category=Shoukaku Class Standard Aircraft Carrier
DropWeight=5
Description=
IllustrationPath=kantai_collection/771_zuikaku_kai