EditionID=minecraft_vanilla_mobs_pack
CardID=038_baby_chestnut_blackdot_horse
RarityLevel=rare
Name=Baby Chestnut Blackdot Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/038_baby_chestnut_blackdot_horse