EditionID=minecraft_vanilla_mobs_pack
CardID=040_baby_chestnut_stockings_horse
RarityLevel=rare
Name=Baby Chestnut Stockings Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/040_baby_chestnut_stockings_horse