EditionID=minecraft_vanilla_mobs_pack
CardID=041_baby_chestnut_whitefield_horse
RarityLevel=rare
Name=Baby Chestnut Whitefield Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/041_baby_chestnut_whitefield_horse