EditionID=minecraft_vanilla_mobs_pack
CardID=042_baby_chestnut_whitespot_horse
RarityLevel=rare
Name=Baby Chestnut Whitespot Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/042_baby_chestnut_whitespot_horse