EditionID=minecraft_vanilla_mobs_pack
CardID=050_baby_creamy_whitefield_horse
RarityLevel=rare
Name=Baby Creamy Whitefield Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/050_baby_creamy_whitefield_horse