EditionID=minecraft_vanilla_mobs_pack
CardID=055_baby_darkbrown_stockings_horse
RarityLevel=rare
Name=Baby Darkbrown Stockings Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/055_baby_darkbrown_stockings_horse