EditionID=minecraft_vanilla_mobs_pack
CardID=056_baby_darkbrown_whitefield_horse
RarityLevel=rare
Name=Baby Darkbrown Whitefield Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/056_baby_darkbrown_whitefield_horse