EditionID=minecraft_vanilla_mobs_pack
CardID=057_baby_darkbrown_whitespot_horse
RarityLevel=rare
Name=Baby Darkbrown Whitespot Horse
Category=Passive Mobs
DropWeight=3
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/057_baby_darkbrown_whitespot_horse