EditionID=minecraft_vanilla_mobs_pack
CardID=185_chestnut_whitefield_horse
RarityLevel=unc
Name=Chestnut Whitefield Horse
Category=Passive Mobs
DropWeight=5
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/185_chestnut_whitefield_horse