EditionID=minecraft_vanilla_mobs_pack
CardID=212_darkbrown_stockings_horse
RarityLevel=unc
Name=Darkbrown Stockings Horse
Category=Passive Mobs
DropWeight=5
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/212_darkbrown_stockings_horse