EditionID=minecraft_vanilla_mobs_pack
CardID=213_darkbrown_whitefield_horse
RarityLevel=unc
Name=Darkbrown Whitefield Horse
Category=Passive Mobs
DropWeight=5
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/213_darkbrown_whitefield_horse