EditionID=minecraft_vanilla_mobs_pack
CardID=214_darkbrown_whitespot_horse
RarityLevel=unc
Name=Darkbrown Whitespot Horse
Category=Passive Mobs
DropWeight=5
Description=Horses are passive mobs that can be ridden when tamed and saddled.
IllustrationPath=minecraft_vanilla_mobs_pack/214_darkbrown_whitespot_horse