
EditionID=inscryption_act3_cardpack
CardID=013_emerald_vessel
RarityLevel=unc

Name=Emerald Vessel
Category=Uncategorized
DropWeight=5

IllustrationPath=inscryption_act3_cardpack/013_emerald_vessel_unc
