
EditionID=inscryption_act3_cardpack
CardID=041_shield_latcher
RarityLevel=com

Name=Shield Latcher
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act3_cardpack/041_shield_latcher_com
