
EditionID=inscryption_act3_cardpack
CardID=047_splinter_cell
RarityLevel=com

Name=Splinter Cell
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act3_cardpack/047_splinter_cell_com
