
EditionID=inscryption_act1_cardpack
CardID=018_child_13_awake
RarityLevel=rare

Name=Child 13 Awake
Category=Uncategorized
DropWeight=3

IllustrationPath=inscryption_act1_cardpack/018_child_13_awake_rare
