
EditionID=inscryption_act1_cardpack
CardID=079_turkey_vulture
RarityLevel=com

Name=Turkey Vulture
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act1_cardpack/079_turkey_vulture_com
