
EditionID=inscryption_act1_cardpack
CardID=089_wriggling_tail
RarityLevel=unc

Name=Wriggling Tail
Category=Uncategorized
DropWeight=5

IllustrationPath=inscryption_act1_cardpack/089_wriggling_tail_unc
