EditionID=inscryption_act2_artpack
CardID=005_automation
RarityLevel=com
Name=Automation
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/005_automation(technology)_com