EditionID=inscryption_act2_artpack
CardID=007_energy_bot
RarityLevel=com
Name=Energy Bot
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/007_energy_bot(technology)_com