EditionID=inscryption_act2_artpack
CardID=011_bolthound
RarityLevel=com
Name=Bolthound
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/011_bolthound(technology)_com