EditionID=inscryption_act2_artpack
CardID=012_bomb_bot
RarityLevel=com
Name=Bomb Bot
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/012_bomb_bot(technology)_com