
EditionID=inscryption_act2_artpack
CardID=022_broken_obal_left
RarityLevel=com

Name=Broken Obal Left
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act2_artpack/022_broken_obal_left_com
