
EditionID=inscryption_act2_artpack
CardID=023_broken_obal_right
RarityLevel=com

Name=Broken Obal Right
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act2_artpack/023_broken_obal_right_com
