
EditionID=inscryption_act2_artpack
CardID=024_energy_conduit
RarityLevel=rare

Name=Energy Conduit
Category=Uncategorized
DropWeight=3

IllustrationPath=inscryption_act2_artpack/024_energy_conduit_rare
