
EditionID=inscryption_act2_artpack
CardID=025_factory_conduit
RarityLevel=com

Name=Factory Conduit
Category=Uncategorized
DropWeight=10

IllustrationPath=inscryption_act2_artpack/025_factory_conduit_com
