EditionID=inscryption_act2_artpack
CardID=025_factory_conduit
RarityLevel=com
Name=Factory Conduit
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/025_factory_conduit(technology)_com