EditionID=inscryption_act2_artpack
CardID=026_heal_conduit
RarityLevel=com
Name=Heal Conduit
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/026_heal_conduit(technology)_com