EditionID=inscryption_act2_artpack
CardID=035_drowned_soul
RarityLevel=rare
Name=Drowned Soul
Category=Undead
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/035_drowned_soul(undead)_rare