EditionID=inscryption_act2_artpack
CardID=038_plasma_jimmy
RarityLevel=rare
Name=Plasma Jimmy
Category=Technology
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/038_plasma_jimmy(technology)_rare