EditionID=inscryption_act2_artpack
CardID=044_hover_mage
RarityLevel=com
Name=Hover Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/044_hover_mage(magicks)_com