EditionID=inscryption_act2_artpack
CardID=045_force_mage
RarityLevel=com
Name=Force Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/045_force_mage(magicks)_com