EditionID=inscryption_act2_artpack
CardID=049_gem_module
RarityLevel=rare
Name=Gem Module
Category=Technology
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/049_gem_module(technology)_rare