EditionID=inscryption_act2_artpack
CardID=050_ghost_ship
RarityLevel=com
Name=Ghost Ship
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/050_ghost_ship(undead)_com