EditionID=inscryption_act2_artpack
CardID=053_grave_digger
RarityLevel=com
Name=Grave Digger
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/053_grave_digger(undead)_com