EditionID=inscryption_act2_artpack
CardID=054_green_mage
RarityLevel=com
Name=Green Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/054_green_mage(magicks)_com