EditionID=inscryption_act2_artpack
CardID=056_double_gunner
RarityLevel=com
Name=Double Gunner
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/056_double_gunner(technology)_com