
EditionID=inscryption_act2_artpack
CardID=058_headless_horseman
RarityLevel=rare

Name=Headless Horseman
Category=Uncategorized
DropWeight=3

IllustrationPath=inscryption_act2_artpack/058_headless_horseman_rare
