EditionID=inscryption_act2_artpack
CardID=062_inspector
RarityLevel=unc
Name=Inspector
Category=Technology
DropWeight=5
Description=
IllustrationPath=inscryption_act2_artpack/062_inspector(technology)_unc