EditionID=inscryption_act2_artpack
CardID=065_great_kraken
RarityLevel=rare
Name=Great Kraken
Category=Nature
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/065_great_kraken(nature)_rare