EditionID=inscryption_act2_artpack
CardID=073_master_bleene
RarityLevel=rare
Name=Master Bleene
Category=Magicks
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/073_master_bleene(magicks)_rare