
EditionID=inscryption_act2_artpack
CardID=073_master_bleene
RarityLevel=rare

Name=Master Bleene
Category=Uncategorized
DropWeight=3

IllustrationPath=inscryption_act2_artpack/073_master_bleene_rare
