
EditionID=inscryption_act2_artpack
CardID=074_master_goranj
RarityLevel=rare

Name=Master Goranj
Category=Uncategorized
DropWeight=3

IllustrationPath=inscryption_act2_artpack/074_master_goranj_rare
