EditionID=inscryption_act2_artpack
CardID=083_moose_buck
RarityLevel=com
Name=Moose Buck
Category=Nature
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/083_moose_buck(nature)_com