EditionID=inscryption_act2_artpack
CardID=085_emerald_mox
RarityLevel=com
Name=Emerald Mox
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/085_emerald_mox(magicks)_com