EditionID=inscryption_act2_artpack
CardID=086_goranj_s_mox
RarityLevel=rare
Name=Goranj's Mox
Category=Magicks
DropWeight=3
Description=
IllustrationPath=inscryption_act2_artpack/086_goranj's_mox(magicks)_rare