EditionID=inscryption_act2_artpack
CardID=093_muscle_mage
RarityLevel=com
Name=Muscle Mage
Category=Magicks
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/093_muscle_mage(magicks)_com