EditionID=inscryption_act2_artpack
CardID=095_null_conduit
RarityLevel=com
Name=Null Conduit
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/095_null_conduit(technology)_com