EditionID=inscryption_act2_artpack
CardID=108_steel_mice
RarityLevel=com
Name=Steel Mice
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/108_steel_mice(technology)_com