EditionID=inscryption_act2_artpack
CardID=111_sarcophagus
RarityLevel=com
Name=Sarcophagus
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/111_sarcophagus(undead)_com