EditionID=inscryption_act2_artpack
CardID=112_sentry_spore
RarityLevel=unc
Name=Sentry Spore
Category=Technology
DropWeight=5
Description=
IllustrationPath=inscryption_act2_artpack/112_sentry_spore(technology)_unc