EditionID=inscryption_act2_artpack
CardID=113_sentry_drone
RarityLevel=com
Name=Sentry Drone
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/113_sentry_drone(technology)_com