EditionID=inscryption_act2_artpack
CardID=116_skelemagus
RarityLevel=com
Name=Skelemagus
Category=Undead
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/116_skelemagus(undead)_com