EditionID=inscryption_act2_artpack
CardID=119_bell_tentacle
RarityLevel=unc
Name=Bell Tentacle
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_artpack/119_bell_tentacle(nature)_unc