EditionID=inscryption_act2_artpack
CardID=120_hand_tentacle
RarityLevel=unc
Name=Hand Tentacle
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_artpack/120_hand_tentacle(nature)_unc