
EditionID=inscryption_act2_artpack
CardID=121_mirror_tentacle
RarityLevel=unc

Name=Mirror Tentacle
Category=Uncategorized
DropWeight=5

IllustrationPath=inscryption_act2_artpack/121_mirror_tentacle_unc
