EditionID=inscryption_act2_artpack
CardID=121_mirror_tentacle
RarityLevel=unc
Name=Mirror Tentacle
Category=Nature
DropWeight=5
Description=
IllustrationPath=inscryption_act2_artpack/121_mirror_tentacle(nature)_unc