EditionID=inscryption_act2_artpack
CardID=125_steambot
RarityLevel=com
Name=Steambot
Category=Technology
DropWeight=10
Description=
IllustrationPath=inscryption_act2_artpack/125_steambot(technology)_com