
EditionID=inscryption_finale_cardpack
CardID=013_sapphire_mox
RarityLevel=unc

Name=Sapphire Mox
Category=Uncategorized
DropWeight=5

IllustrationPath=inscryption_finale_cardpack/013_sapphire_mox_unc
